---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: control

appservers:
  hosts:
    appserver-vm:
      ansible_host: APP_SERVER_PUBLIC_IP
      ansible_user: YOUR_USER
      ansible_ssh_private_key_file: ~/.ssh/YOUR_KEY
    docker-vm:
      ansible_host: DOCKER_SERVER_PUBLIC_IP
      ansible_user: YOUR_USER
      ansible_ssh_private_key_file: ~/.ssh/YOUR_KEY

dbservers:
  hosts:
    dbserver-vm:
      ansible_host: DB_SERVER_PUBLIC_IP
      ansible_user: YOUR_USER
      ansible_ssh_private_key_file: ~/.ssh/YOUR_KEY

