---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: control

appservers:
  hosts:
    appserver-vm:
      ansible_host: 34.134.224.219
      ansible_user: konstantinos
      ansible_ssh_private_key_file: /home/konstantinos/.ssh/vmdatabase03
    docker-vm:
      ansible_host: 146.148.49.7
      ansible_user: konstantinos
      ansible_ssh_private_key_file: /home/konstantinos/.ssh/vmdatabase03

      

dbservers:
  hosts:
    dbserver-vm:
      ansible_host: 34.136.8.7
      ansible_user: konstantinos
      ansible_ssh_private_key_file: /home/konstantinos/.ssh/vmdatabase03
