---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: control

appservers:
  hosts:
    appserver-vm:
      ansible_host: 34.60.110.107
      ansible_user: konstantinos
      ansible_ssh_private_key_file: /home/konstantinos/.ssh/vmdatabase03
    docker-vm:
      ansible_host: 34.56.225.14
      ansible_user: konstantinos
      ansible_ssh_private_key_file: /home/konstantinos/.ssh/vmdatabase03

      

dbservers:
  hosts:
    dbserver-vm:
      ansible_host: 34.30.231.84
      ansible_user: konstantinos
      ansible_ssh_private_key_file: /home/konstantinos/.ssh/vmdatabase03
